services:
  pi-dashcam:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
        # GOARCH: arm
        # GOARM: 7
      args:
          GOARCH: amd64
          GOOS: linux
    container_name: pi-dashcam
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # Mount video directory to host
      - dashcam-videos:/var/lib/pi-dashcam/videos
      # Mount config
      - dashcam-config:/etc/pi-dashcam
    environment:
      - LOG_LEVEL=info
    devices:
      # Raspberry Pi Camera?
      # - /dev/vcsm-cma:/dev/vcsm-cma
      # - /dev/vchiq:/dev/vchiq
      # Mount with read-write permissions
      - /dev/video0:/dev/video0:rw
    # Run with privileged mode to access camera devices
    privileged: true
    networks:
      - dashcam-network

volumes:
  dashcam-videos:
    driver: local
  dashcam-config:
    driver: local

networks:
  dashcam-network:
    driver: bridge
